providers = []

[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'corepack enable',
  'pnpm install --frozen-lockfile'
]
dependsOn = ['setup']

[phases.build]
cmds = [
  'pnpm run build'
]
dependsOn = ['install']

[start]
cmd = 'pnpm run start'
