[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]
dependsOn = ["setup"]

[phases.build]
cmds = [
  "pnpm --filter config build",
  "pnpm --filter domain build",
  "pnpm --filter lib build",
  "pnpm --filter ${RAILWAY_BUILD_TARGET} build"
]
dependsOn = ["install"]

[start]
cmd = "pnpm --filter ${RAILWAY_BUILD_TARGET} start"
