# Railway Configuration for 誠憶鮮蔬外送系統
[build]
builder = "nixpacks"
watchPatterns = ["src/**", "views/**", "public/**", "package.json", "railway.toml", "*.sql", "*.js", "*.md"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
replicas = 1

# 強制重建標記 - 2025-09-10
[variables.rebuild]
FORCE_REBUILD = "2025-09-10-fix"

[variables]
# Node.js 生產環境設定
NODE_ENV = "production"
PORT = "3000"

# 系統設定
ADMIN_EMAIL = "shnfred555283@gmail.com" 
ADMIN_PASSWORD = "admin123"
SYSTEM_NAME = "誠憶鮮蔬外送系統"

# LINE Bot 設定 (需要在Railway中設置)
# LINE_CHANNEL_ACCESS_TOKEN = "your_token"
# LINE_CHANNEL_SECRET = "your_secret"

# Google Maps API (需要在Railway中設置)  
# GOOGLE_MAPS_API_KEY = "your_api_key"

# 資料庫設定（Railway將自動提供）
# DATABASE_URL - Railway PostgreSQL自動設置
# REDIS_URL - Railway Redis自動設置 (可選)