# Railway Configuration for 誠憶鮮蔬外送系統
[build]
builder = "nixpacks"
watchPatterns = ["src/**", "views/**", "public/**", "package.json", "railway.toml", "*.sql", "*.js", "*.md"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
replicas = 1

# 強制重建標記 - 2025-09-10
[variables.rebuild]
FORCE_REBUILD = "2025-09-10-fix"

[variables]
# Node.js 生產環境設定
NODE_ENV = "production"
PORT = "3000"

# 系統設定
ADMIN_EMAIL = "shnfred555283@gmail.com" 
ADMIN_PASSWORD = "admin123"
SYSTEM_NAME = "誠憶鮮蔬外送系統"

# LINE Bot 設定
LINE_CHANNEL_ID = "2007891772"
LINE_CHANNEL_SECRET = "35bc80bb75f95d22a49aaaf8772eef38"
LINE_CHANNEL_ACCESS_TOKEN = "Rb4HdoTx3gV7skydMOJy4/0xw09IpOc9djST7z5eSEs+CccUAfsdtrPlI3SEEQya+Npz6+OW6B8un+Tfr6sJ6dw3Aab1Y+kLng21ZAXjO0sYYS7ILLzH4ccNVRDh8Xnv3ch0DTDNGT8pc+7bGZjruAdB04t89/1O/w1cDnyilFU="
LINE_LIFF_ID = "2007966099-qXjNxbXN"

# Google Maps API
GOOGLE_MAPS_API_KEY = "AIzaSyBRwW-NMUDGMXaDhvl3oYJs_OqjfXWTTNE"

# 資料庫設定（Railway將自動提供）
# DATABASE_URL - Railway PostgreSQL自動設置
# REDIS_URL - Railway Redis自動設置 (可選)