version: '3.9'

services:
  api:
    build:
      context: ../
      dockerfile: infra/dockerfiles/api.Dockerfile
    env_file: ../.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ../
      dockerfile: infra/dockerfiles/web.Dockerfile
    env_file: ../.env
    ports:
      - "3001:3000"
    depends_on:
      - api

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chengyi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
