[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]
dependsOn = ["setup"]

[phases.build]
cmds = [
  "pnpm --filter config build",
  "pnpm --filter domain build",
  "pnpm --filter lib build",
  "pnpm --filter api build"
]
dependsOn = ["install"]

[start]
cmd = "pnpm --filter api start"
