[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'corepack enable',
  'pnpm install --frozen-lockfile'
]
dependsOn = ['setup']

[phases.build]
cmds = [
  'pnpm --filter config build',
  'pnpm --filter domain build',
  'pnpm --filter lib build',
  'pnpm --filter api build'
]
dependsOn = ['install']

[start]
cmd = 'pnpm --filter api start'
